### ISSUE TITLE
Switch order of table of contents for tables and figures

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#19]
https://github.com/nwfsc-assess/sa4ss/blob/4d910250fd0355a30bbfc01d775ddce8d18ca224/inst/rmarkdown/templates/sa/resources/sadraft.tex#L332

I think the standard order for the back of the document is tables (e.g. 52tables) and then figures (e.g., 53figure, although this can be changed by changing the file number). However, the the sadraft puts the table of contents as figures then tables.  I think just switching the order of these here would put these items in alignment.  The one question I do have whether or not a user would need to redraft a document in order to change this order or if there is something than can be revised in the files created by the draft function?  Thanks

**Comment by aaronmberger-nwfsc** [comment]
Related, is there a recommendation in the TOR (or otherwise) to put the list of figures and list of tables at the very beginning of the document?  Although it is nice and tidy there; I find it a bit weird that the executive summary (which is usually the first thing someone wants to read) actually starts on something like page 20 because the list of figures and tables for stock assessment documents are so long.  Other documents that use this format usually only have like a page for each so more tractable in those situations.  No big deal for now, but just curious if others thought scrolling for many pages just to reach the exec summary was not ideal?

**Comment by iantaylor-NOAA** [comment]
I don't know what sa4ss supports, but I was really happy with the amount of detail in the BigSkate table of contents that @andi-stephens-NOAA created using subsections within the figures and tables and setting `toc_depth: 4`:
https://github.com/andi-stephens-NOAA/BigSkate_Doc/blob/master/Big_Skate_2019.Rmd#L16-L17
![image](https://user-images.githubusercontent.com/4992918/114222524-8e958200-9923-11eb-8e1d-e0ec6a6ad210.png)

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa for the question and @aaronmberger-nwfsc for the suggestion. I would like to go forward with removing the list of table and figures because it is NOT required in the TOR. @chantelwetzel-noaa are you okay with just removing it rather than changing the order?

**Comment by aaronmberger-nwfsc** [comment]
I think they are two different things @kellijohnson-NOAA, and this mix up is my bad as I should have started a new issue.  I think Chantel is suggesting the order of Tables and Figures in the Table of Contents be switched such that in the main document after the text there is then a Tables section and then a Figures Section.  

My suggestion was to move the List of Tables and List of Figures to a different spot (not sure where is best), because these lists are so long that the executive summary is no where near the beginning of the document (though admittedly I don't know if this an sa4ss setup or maybe just Dover sole specific?).  If this doesn't make sense, I'm guessing its a Dover sole only thing.

**Comment by kellijohnson-NOAA** [comment]
I think the order of things in the table of contents is correct because of how the markdown files are named, but with b0aee93 I removed the list of tables and figures.

@chantelwetzel-noaa are you okay with just removing it rather than changing the order of the lists and is the TOC in the correct order for you?

**Comment by chantelwetzel-noaa** [comment]
Yup.  I ended up removing this from the packaged skeleton.
