### ISSUE TITLE
Add instructions for using acronyms and option to include a glossary of acronyms used

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/sa4ss#20]
Use of the glossaries package (https://ctan.org/pkg/glossaries) seems like a great way to deal with acronyms. 
However, it would be useful to provide some instruction in the README about theuse of `\Gls{}` and `\gls{}` and/or a suggestion to go read the [Beginners' Guide](https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/glossaries/glossariesbegin.pdf) to that package.

These shortcuts are in frequent use in the skeleton files like https://github.com/nwfsc-assess/sa4ss/blob/4d910250fd0355a30bbfc01d775ddce8d18ca224/inst/rmarkdown/templates/sa/skeleton/21s-ccfrp.Rmd#L3 and I see that @chantelwetzel-noaa used them throughout the Dover Sole assessment: https://github.com/chantelwetzel-noaa/dover_sole_2021/search?q=gls.

I also find having a glossary of acronyms used in assessment report to be useful so adding this automatically via glossaries would be great. I don't know enough about the package to guess which of the 4 options for doing so would make sense (if any): https://mirrors.concertpass.com/tex-archive/macros/latex/contrib/glossaries/glossariesbegin.pdf#page=17.

Note #14 is a separate issue related to where the acronyms get defined.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for mentioning this. Sometimes I forget to document additions along the way, which would have clearly been helpful here.

I have since added a short introduction to the glossary package in the [sa4ss readme](https://github.com/nwfsc-assess/sa4ss/blob/master/README.md) that will hopefully be helpful to users and point them to the main documentation as well. 

Note that I removed the enhancement label because I am going to make a separate issue for the addition of a glossary and the remainder of this issue will just be for documenting the use of the package.
